package muc.project.model;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import muc.project.model.Client_AccessPoint;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CLIENT_AP".
*/
public class Client_AccessPointDao extends AbstractDao<Client_AccessPoint, Long> {

    public static final String TABLENAME = "CLIENT_AP";

    /**
     * Properties of entity Client_AccessPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ClientId = new Property(1, Long.class, "clientId", false, "CLIENT_ID");
        public final static Property AccessPointId = new Property(2, Long.class, "accessPointId", false, "ACCESS_POINT_ID");
    };

    private DaoSession daoSession;

    private Query<Client_AccessPoint> client_ClientAccessPointQuery;
    private Query<Client_AccessPoint> accessPoint_ClientAccessPointQuery;

    public Client_AccessPointDao(DaoConfig config) {
        super(config);
    }
    
    public Client_AccessPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CLIENT_AP\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CLIENT_ID\" INTEGER," + // 1: clientId
                "\"ACCESS_POINT_ID\" INTEGER);"); // 2: accessPointId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CLIENT_AP\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Client_AccessPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long clientId = entity.getClientId();
        if (clientId != null) {
            stmt.bindLong(2, clientId);
        }
 
        Long accessPointId = entity.getAccessPointId();
        if (accessPointId != null) {
            stmt.bindLong(3, accessPointId);
        }
    }

    @Override
    protected void attachEntity(Client_AccessPoint entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Client_AccessPoint readEntity(Cursor cursor, int offset) {
        Client_AccessPoint entity = new Client_AccessPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // clientId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // accessPointId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Client_AccessPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setClientId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setAccessPointId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Client_AccessPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Client_AccessPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "clientAccessPoint" to-many relationship of Client. */
    public List<Client_AccessPoint> _queryClient_ClientAccessPoint(Long clientId) {
        synchronized (this) {
            if (client_ClientAccessPointQuery == null) {
                QueryBuilder<Client_AccessPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ClientId.eq(null));
                client_ClientAccessPointQuery = queryBuilder.build();
            }
        }
        Query<Client_AccessPoint> query = client_ClientAccessPointQuery.forCurrentThread();
        query.setParameter(0, clientId);
        return query.list();
    }

    /** Internal query to resolve the "clientAccessPoint" to-many relationship of AccessPoint. */
    public List<Client_AccessPoint> _queryAccessPoint_ClientAccessPoint(Long accessPointId) {
        synchronized (this) {
            if (accessPoint_ClientAccessPointQuery == null) {
                QueryBuilder<Client_AccessPoint> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AccessPointId.eq(null));
                accessPoint_ClientAccessPointQuery = queryBuilder.build();
            }
        }
        Query<Client_AccessPoint> query = accessPoint_ClientAccessPointQuery.forCurrentThread();
        query.setParameter(0, accessPointId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getClientDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAccessPointDao().getAllColumns());
            builder.append(" FROM CLIENT_AP T");
            builder.append(" LEFT JOIN CLIENT T0 ON T.\"CLIENT_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ACCESS_POINT T1 ON T.\"ACCESS_POINT_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Client_AccessPoint loadCurrentDeep(Cursor cursor, boolean lock) {
        Client_AccessPoint entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Client client = loadCurrentOther(daoSession.getClientDao(), cursor, offset);
        entity.setClient(client);
        offset += daoSession.getClientDao().getAllColumns().length;

        AccessPoint accessPoint = loadCurrentOther(daoSession.getAccessPointDao(), cursor, offset);
        entity.setAccessPoint(accessPoint);

        return entity;    
    }

    public Client_AccessPoint loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Client_AccessPoint> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Client_AccessPoint> list = new ArrayList<Client_AccessPoint>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Client_AccessPoint> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Client_AccessPoint> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
